### ISSUE TITLE
Project Path Could Not be Selected

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#188]
When I created a new project today I couldn't select the project path as usual. Instead it was locked to the VIAN folder.

**Comment by ghalter** [comment]
If this appears again, reopen this issue

**Comment by pajarola** [comment]
Hoi Gaudenz,

Ich denke ich kann mich mal aus den project emails ausklinken. Kannst du das machen oder muss ich das selbst?

Gruss, Renato

> On 19. Aug. 2019, at 14:36, Gaudenz Halter <notifications@github.com> wrote:
> 
> If this appears again, reopen this issue
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Prof. Dr. Renato Pajarola
Visualization and MultiMedia Lab
Department of Informatics
University of Zürich                                            

pajarola@ifi.uzh.ch
http://vmml.ifi.uzh.ch/
http://www.facebook.com/uzh.ifi/

**Comment by ghalter** [comment]
Hoi Renato,

Ah sorry, ja da hat dein Email Client wohl Sturm geläutet in der letzten Halbstunde.
Habe dich raus genommen.  Der Github ist ja nun sowieso öffentlich.

Gruss Gaudenz

**Comment by pajarola** [comment]
Danke. :-)

> On 19. Aug. 2019, at 14:40, Gaudenz Halter <notifications@github.com> wrote:
> 
> Hoi Renato,
> 
> Ah sorry, ja da hat dein Email Client wohl Sturm geläutet in der letzten Halbstunde.
> Habe dich raus genommen. Der Github ist ja nun sowieso öffentlich.
> 
> Gruss Gaudenz
> 
> From: pajarola<mailto:notifications@github.com>
> Sent: Montag, 19. August 2019 14:37
> To: ghalter/VIAN<mailto:VIAN@noreply.github.com>
> Cc: Gaudenz Halter<mailto:gaudenz.halter@live.com>; State change<mailto:state_change@noreply.github.com>
> Subject: Re: [ghalter/VIAN] Project Path Could Not be Selected (#188)
> 
> Hoi Gaudenz,
> 
> Ich denke ich kann mich mal aus den project emails ausklinken. Kannst du das machen oder muss ich das selbst?
> 
> Gruss, Renato
> 
> > On 19. Aug. 2019, at 14:36, Gaudenz Halter <notifications@github.com> wrote:
> >
> > If this appears again, reopen this issue
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> 
> --
> Prof. Dr. Renato Pajarola
> Visualization and MultiMedia Lab
> Department of Informatics
> University of Zürich
> 
> pajarola@ifi.uzh.ch
> http://vmml.ifi.uzh.ch/
> http://www.facebook.com/uzh.ifi/
> 
> 
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fghalter%2FVIAN%2Fissues%2F188%3Femail_source%3Dnotifications%26email_token%3DADQS6GZOHMHWJGGWENVSPI3QFKHYXA5CNFSM4FZFJF4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4SYOBQ%23issuecomment-522553094&data=02%7C01%7C%7C3d4360758f874c303e6808d724a2010e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637018150527070482&sdata=%2BUMYf1zi9zLYSQfauiKgDIUBStJn2ZN47QLE2zXG2iE%3D&reserved=0>, or mute the thread<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQS6GYO6ZSY6JLTH4FDEJDQFKHYXANCNFSM4FZFJF4A&data=02%7C01%7C%7C3d4360758f874c303e6808d724a2010e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637018150527080493&sdata=M088%2FuK4l7aMchIA0wSlMfc1UYu4oJpwTztQMkUwIRU%3D&reserved=0>.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Prof. Dr. Renato Pajarola
Visualization and MultiMedia Lab
Department of Informatics
University of Zürich                                            

pajarola@ifi.uzh.ch
http://vmml.ifi.uzh.ch/
http://www.facebook.com/uzh.ifi/
