### ISSUE TITLE
Films Cannot Be Selected

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#205]
**Describe the bug**
Films cannot be selected in corpus visualizer, only segments.

<img width="1280" alt="screen shot 2019-01-09 at 00 05 32" src="https://user-images.githubusercontent.com/30805626/50864433-50a2ff80-13a2-11e9-87d3-ec460629f4a2.png">

**Comment by ghalter** [comment]
This seems to be resolved by now
