### ISSUE TITLE
Grid Not Visible in Exported Visualizations

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#206]
**Describe the bug**
Contrary to visualizations as they appear in the corpus visualizer, grids are not visible in the exported visualizations.

<img width="655" alt="screen shot 2019-01-09 at 00 08 54" src="https://user-images.githubusercontent.com/30805626/50864635-f48cab00-13a2-11e9-9928-bf2e79f2a85e.png">
![moodlighting_corpus_os_images](https://user-images.githubusercontent.com/30805626/50864687-1e45d200-13a3-11e9-98b0-7063798e9ecb.png)

**Comment by ghalter** [comment]
This is resolved
