### ISSUE TITLE
Crash After Chosing Chroma in Color_dT

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#209]
**Describe the bug**
VIAN crashed after I chose chroma in Color_dT

**To Reproduce**
1. Go to Visualization
2. Click on Color_dT
3. Chose Chroma instead of Saturation

**Console Log**
LOG:  ClassificationObjectChangedJob finished
IProjectChangeNotify: Not Implemented <core.gui.screenshot_manager.ScreenshotsManagerDockWidget object at 0x1c33b0b558>
'UniqueKeyword' object has no attribute 'word'
LOG:  ClassificationObjectChangedJob finished
IProjectChangeNotify: Not Implemented by  <core.gui.screenshot_manager.ScreenshotsManagerDockWidget object at 0x1c33b0b558>
Init: 1472309392 (50, 250, 445, 4) <class 'numpy.uint8'>
IProjectChangeNotify: Not Implemented <core.gui.screenshot_manager.ScreenshotsManagerDockWidget object at 0x1c33b0b558>
'UniqueKeyword' object has no attribute 'word'
LOG:  ClassificationObjectChangedJob finished
Saving Project  has no job()
/Users/baflue/Documents/ERC_FilmColors/Analysetool/Korpus_Filme/14_Une_Femme_est_une_Femme_1961/14_1_1_Une femme est une femme
LOG:  Project Saved
(<class 'AttributeError'>, AttributeError("'ScreenshotsManagerDockWidget' object has no attribute 'draw_visualizations'",), <traceback object at 0x1c40377bc8>)
Traceback (most recent call last):
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/gui/screenshot_manager.py", line 269, in color_dt_mode_changed
    self.draw_visualizations()
AttributeError: 'ScreenshotsManagerDockWidget' object has no attribute 'draw_visualizations'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ghalter** [comment]
This is fixed by now
