### ISSUE TITLE
Feature: Adjustment of scaling of Color_dT and Color_dY

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#210]
**Problem to solve**
Scaling in Color_dT and Color_dY should be both more stable and more flexible. 

**Solution to the problem**
More flexible: extend x and y range.

More stable: same scales should render same scales for bg, fg, global or different year ranges of the same extension, i.e. 30 years.

**Comment by ghalter** [comment]
This is by now more stable, horizontal scaling is completely removed
