### ISSUE TITLE
Scaling in Color_dT Plot Malfunction

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#211]
**Describe the bug**
In 1684_1_1_LesDemoisellesDeRochefort_1967_DVD_VIAN_GH the Color_dT plot was available but not adjustable to the usual scale, for instance y-axis remained mostly flat in saturation channel, images were small.

**To Reproduce**
1. Go to Color_dT plot
2. Click on global' etc.
3. Adjust Plot Controls
4. See error in Screenshots

**Console Log**
No log available?

**Expected behavior**
<img width="701" alt="screen shot 2019-01-25 at 13 17 07" src="https://user-images.githubusercontent.com/30805626/51745871-8a634e00-20a4-11e9-8c34-04e7bb7f326d.png">
<img width="691" alt="screen shot 2019-01-25 at 13 16 20" src="https://user-images.githubusercontent.com/30805626/51745872-8a634e00-20a4-11e9-9d15-3b5906aa9246.png">

I wanted to adjust the plot to the usual scale.

**Screenshots**
Attached

**Comment by ghalter** [comment]
This is now implemented as well in the latest visualization updates. The scaling has been removed
