### ISSUE TITLE
Feature: Sort and improve consistency in classification

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#223]
**Problem to solve**

1. Classification core concepts should be sorted in an improved fashion from top priorities to lower priorities.

2. Lighting should be one core concept containing all the lighting concepts.

3. Where are the materials / tectures of objects?

4. Background / environment distinction?

5. Order / grouping of concepts

6. "ELAN Data" is an old concept that should be replaced by "Location / Time"

7. Place "significance" always in top position

<img width="906" alt="Screen Shot 2019-10-14 at 11 57 53" src="https://user-images.githubusercontent.com/30805626/66743456-3d194d80-ee7a-11e9-91df-c8a3cbe532d9.png">
![Screen Shot 2019-10-14 at 11 48 39](https://user-images.githubusercontent.com/30805626/66743457-3d194d80-ee7a-11e9-808e-c9c698d88f8f.png)

**Comment by flueko** [comment]
Is this topic resolved in the new version of VIAN? Resasonable sorting is crucial for a smooth workflow.

**Comment by ghalter** [comment]
This seems to be solved for now. 
If this ever comes up again, we can open a new issue
