### ISSUE TITLE
Feature: Add Remarks to Classification

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#225]
**Problem to solve**
In FileMaker we had a for each register a field "remarks" to write down specific observations. It just occurs to me that this is nnot available in VIAN's classification yet. (And also not imported to the VIAN WebApp (where it should be available only to the research group)

**Solution to the problem**
Please add a field remarks to each of the registers, for example "remarks composition".
<img width="932" alt="Screen Shot 2019-10-14 at 22 52 15" src="https://user-images.githubusercontent.com/30805626/66782217-7cc15300-eed5-11e9-84fc-7e986e2a25a1.png">

**Comment by ghalter** [comment]
Sadly, this is not solvable in a neat and simple way, due to how the Registers (Vocabulary.category in VIAN) are implemented.

**Comment by flueko** [comment]
Another way would be to copy the segmentation and to add the remarks there in the form of annotations. What do you think @ghalter ?

And would there be a way to import these comments into the VIAN WebApp?

**Comment by ghalter** [comment]
Yes, essentially there are three ways to implement this, 

1. We create a new data structure which allows creating notes per selector and vocabulary category. This is however very usecase specific, and does not serve other purposes than exactly this one. 

2. We extend VIANs segmentation system, allowing parent and child segmentations, for each category we would introduce a new child segmentation. (In this case we would only have to extend this functionality, however it increases the complexity of VIAN) 

3. We allow the user to define multiple annotations within one segment. i.e. a user can define different text blocks within a segment. Double clicking on the segment (which currently just shows a single textbox to put the annotation in) would be extended, enabling the user to define multiple text annotations. 


Personally I favor variant 2 or 3, 3 is probably the simplest to implement and the most lightweight. It however introduces a concept users are not familiar with, user of ELAN would probably better understand variant 2. 

@flueko What do you think?

**Comment by ghalter** [comment]
This is now integrated via, multi-annotation. 
Currently, there is no way of templating the different annotations within a Segmentation, 
but this could be added in the future.

**Comment by ghalter** [comment]
@flueko regarding #286: 


Yes, this is now possible via the "multi-annotation" mode which can be activated in the Timeline via: 
![grafik](https://user-images.githubusercontent.com/14757659/82673559-5a00d500-9c42-11ea-9088-9f050624a5b7.png)

Multiple Annotation Entries can now be added to the segment, this also corresponds to the 
W3C for WebAnnotation: 
![grafik](https://user-images.githubusercontent.com/14757659/82673736-8d436400-9c42-11ea-9c71-53d281bb2b64.png)

It is however currently not finished in implementation and thus by default not turned on.

**Comment by JonathanSchaber** [comment]
renaming the annotation seems not to work at the moment
![renaming_annotation](https://user-images.githubusercontent.com/54320492/98556653-92a17300-22a3-11eb-8992-afa776ba77f1.png)

**Comment by ghalter** [comment]
@JonathanSchaber 
Could you check on the current version if there is anything else to improve?
