### ISSUE TITLE
additional color scheme visualizations

### ISSUE THREAD

**Issue by olivood** [ghalter/VIAN#226]
**Problem to solve**
The Z-Projections are fine, but also eye-catching are the so-called Moviebarcodes and the Mosaic-Designs. 

**Solution to the problem**
Add Moviebarcodes and Mosaic-Desigsn to the visualizations right at the top of the page.

![image](https://user-images.githubusercontent.com/45812935/67847712-97194480-fb03-11e9-8810-7082ae072284.png)

[image](https://user-images.githubusercontent.com/45812935/67847642-7bae3980-fb03-11e9-8b0d-608ec2587287.png)

**Comment by flueko** [comment]
Relates to the **VIAN WebApp.** -->

**Comment by ghalter** [comment]
I migrate this to the WebApp, since it does not relate to VIAN
