### ISSUE TITLE
screenshotManager: after deleting screen shots automatically scrolls back to top 

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#232]
**Describe the bug**
after deleting screen shots automatically going back to top of screenshots and not staying the actual place. 

**To Reproduce**
1. Go to Screenshots
2. select any screenshots
3. delete it
4. then you are on the top of the screenshot.

**Console Log**
no log

**Expected behavior**
It would be better if I could stay at the place, where I originally was, when I have to delete a lot of screenshots, otherwise I have to start from the top again. 

Thank you!!!

**Comment by ghalter** [comment]
This is because VIAN redraws the complete layout after a deletion or insertion operation. Shortterm we can scroll to the closest screenshot.

 Longterm, we should think about omiting the time consuming complete redraw.

**Comment by ghalter** [comment]
The screenshot manager now moves back to the original location
