### ISSUE TITLE
Feature: Nomenclature Movie Segment Export

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#238]
The Movie segment export is a super feature, however right now I cannot give it a proper name during export, instead it just gets a number.

**Comment by ghalter** [comment]
Yes, we could indeed use the same nomenclature builder as for screenshots, 
although this feature seems to be broken see #237

**Comment by ghalter** [comment]
The Nomenclature is now 

`<Movie-ID>_<Segmentation-Name>_<Segment-ID>.[mp4]`

**Comment by ghalter** [comment]
Thinking about a nomenclature editor can be done a different time. I think currently, a fixed nomenclature is sufficient.
