### ISSUE TITLE
Sound Movie Segment Export

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#239]
Today I noticed that the sound in exported clips is only working in VLC, not QuickTime, not when embedded in PowerPoint. 

Martin identified the problem and transcoded the clips for me.

Otherwise the movie export is a great option!

**Comment by flueko** [comment]
Is it complicated to fix the problem? Because otherwise I would like to use the feature quite often.

**Comment by ghalter** [comment]
No, this should not be a big deal, I however have to check how moviepy exports audio codecs, for now, the sound is only not available in QuickTime as far as I know. 

I will check this next week.

**Comment by ghalter** [comment]
Forcing aac audio codec on osx, this has to be tested on osx first:

**Comment by flueko** [comment]
Should I test?

**Comment by ghalter** [comment]
Yes please.

**Comment by ghalter** [comment]
I also raised the bitrate of the exported movie to a meaningful value, since the compression was way to strong.
