### ISSUE TITLE
Vocabulary Rework

### ISSUE THREAD

**Issue by ghalter** [ghalter/VIAN#244]
Vocabulary Management and Classification Object Management is rather tedious currently. 
It also has several Bug, including Vocabularies not in Sync with the FileSystem. 

I think best is to overhaul this system once again: 

1. Remove the step to attach vocabularies to the project, this should simply be done once attached to the classification object. 
2. A "Global" classification object should always be present to simplify getting started with classification
3. The Vocabulary Manager View should be integrated into the Experiment Setup View. 
4. Either Classification Objects can be hierarchically structure or not, currently this is half-supported, being inclear to the user

**Comment by ghalter** [comment]
After a discussion, @JonathanSchaber and I agreed, that a manual step of attaching vocabularies to a project is currently the best solution, since there are many possible conflicts which could happen during exchange.

**Comment by ghalter** [comment]
Either Classification Objects can be hierarchically structure or not, currently this is half-supported, being inclear to the user. 

We keep this feature for now, as it is serialized correctly, 
Semantic Segmentation is however nto yet inherited. This will be future work.

**Comment by JonathanSchaber** [comment]
Experiment now really much clearer how things go together.
Minor bug in the vocabulary manager: When creating a new vocabulary, name gets not updated only until vocabulary gets drag & dropped to the project.

**Comment by ghalter** [comment]
You mean, it doesn't get updated in the Project when renaming it in the Library?
