### ISSUE TITLE
Unified Search View

### ISSUE THREAD

**Issue by ghalter** [ghalter/VIAN#247]
**Problem to solve**
VIAN currently has some rather limited search capabilities. 
This is simply not treated as very important until now, however, searching within projects and local corpora is highly relevant to make VIAN more attractive for other use-cases. 

**Solution to the problem**
Include a general search window into VIAN (CTRL + Shift + F) 
Allows: 

1. Searching Text in Segmentation
2. Searching Text in Notes
3. Searching for Keywords
4. Create Visualizations in WebView

**Additional context**

**Comment by JonathanSchaber** [comment]
Nice new feature!
Point to enhance: If annotations are being searched (eg: «exterior») the should also be displayed, if matching.

**Comment by JonathanSchaber** [comment]
Small bug: if search window is closed and re-opened, the old search results are still being displayed.

**Comment by ghalter** [comment]
> Small bug: if search window is closed and re-opened, the old search results are still being displayed.

This is actually intended, so that when one closes the search and wants to go back to it, the query hasn't vanished. Do you think it feels like a bug? 

> Point to enhance: If annotations are being searched (eg: «exterior») they should also be displayed, if matching.

Yes I will highlight where it has been found

**Comment by JonathanSchaber** [comment]
Ah, no, if the intent is to keep the old query, then it's fine, but then the old query should also re-appear, not just the results

**Comment by ghalter** [comment]
This is included, I'll keep this issue open for further improvements and discussion, but remove it from the milestone, since the primary goal has been achieved.
