### ISSUE TITLE
Segment Order scrambled

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#257]
The segment IDs are messed up, how can I fix it and why did it happen?
![Screen Shot 2020-03-08 at 22 42 20](https://user-images.githubusercontent.com/30805626/76171796-894d8d00-618f-11ea-961f-664b34c79831.png)

**Comment by ghalter** [comment]
Did you try removing and adding the segment again? If this doesn't help, please post the .eext file here.

**Comment by ghalter** [comment]
I added a recomputation of segments on project load, I can however not recreate the issue. 
if it arises again, we can open this issue again
