### ISSUE TITLE
Feature: can a screenshot list remains at a current position, instead of going back to the first line?

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#260]
Every time when I make a new screen shot manually or delete any screenshots in the list, window goes back to the top of the list. It would be more convenient, when the window could remain at the current position?

**Comment by ghalter** [comment]
This is already implemented, and will be in the next release: 
#232

**Comment by ghalter** [comment]
If this remains a problem, we can reopen the Issue
