### ISSUE TITLE
Exporting Selected Screenshot only

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#261]
Momentan ist es nur möglich, alle Screenshots auf einmal zu exportieren.
Eventuell eine Exportoption (Rechtsklick im Outliner oder so) für einzelne Entitäten implementieren?

**Comment by ghalter** [comment]
Can you check again and close the issue if resolved

**Comment by JonathanSchaber** [comment]
Should the functionality already be implemented? Can't find it..

**Comment by ghalter** [comment]
Currently, it simply works by selecting Screenshots and than pressing Export Screenshots, 
We could of course create a second function "Export Selected".

**Comment by ghalter** [comment]
I will close this issue for now, if there is the need for a better user interaction, we can reopen it @JonathanSchaber
