### ISSUE TITLE
create a subcorpora based on queries

### ISSUE THREAD

**Issue by Blameris** [ghalter/VIAN#264]
**Problem to solve**
I cannot create subcorpora based on queries, although it would help me to refine queries when I am able to safe a query and than do various other queries within that corpus.
 
**Solution to the problem**
Have a button in the query field that says creat subcorpus, have a subcorpus created based on the results of the query, ask for name of the subcorpus and have the subcorpus saved within my account 

**Additional context**
--

**Comment by ghalter** [comment]
This is a very good idea, but refers to the WebApp. 
https://github.com/ghalter/VIAN-Web. This issue should be migrated

**Comment by Blameris** [comment]
Link does not work

**Comment by Blameris** [comment]
I copied it to vian-web. can I delete this here?

**Comment by ghalter** [comment]
Yes, you can usually write something like. 
"this is resolved" and then press "close and comment "
