### ISSUE TITLE
Movie ID cannot be changed in Inspector and now automatically saved as "99"

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#268]
**Describe the bug**
I have by mistake saved the wrong Movie ID when I created a new project.
Not only my correction in ispector afterwards could bring any change in a system, but also the Movie ID is now somehow automatically changed into "99". As a result screenshots got also the wrong ID after export. Anyway, now I can type only two numbers there. 
The correct Movie ID is in this case 4554.  

**To Reproduce**
**Console Log**

**Expected behavior**
I want to set up the right Movie ID. 

**Screenshots**
![Anmerkung 2020-03-24 120502](https://user-images.githubusercontent.com/58776405/77419877-6810b180-6dc9-11ea-933e-963e90ee5350.png)

**Desktop (please complete the following information):**
 - OS: intel Core i7 8th Gen.
 - Browser chrome

**Additional context**

**Comment by ghalter** [comment]
This was a wrong range limitation in the UI and has been fixed
