### ISSUE TITLE
Auto Screenshots - most informative doesn't work

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#271]
**Describe the bug**
Tools - Auto Screenshots - "most informative" - if I chose this, nothing happens. 
Only "uniform distribution" works. 

**Desktop (please complete the following information):**
 - OS: [windows 10, intel core i7 8th gen.]
 - Browser [chrome]

**Comment by ghalter** [comment]
Indeed, this has been because if there is no colorimetry present, VIAN will silently not do it. 
Added functionality to automatically process this if not present

**Comment by ghalter** [comment]
As reported by @megumihayakawa85, this can also occure when the Colorimetry has been computed, 
which may link to a still present problem, that VIAN sometimes does not detect correctly if the colorimetry has been performed completely. 

I opened a new issue for this problem: 
#273
