### ISSUE TITLE
notes to the segments are overwritten 

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#282]
**Describe the bug**
Once you take a note to the segment directly and save, when you want to add something later, a empty box is open and it will be just overwritten. The already saved notes are not applied to a new box.    

**To Reproduce**
1. double click any segement and write something. 
2. save it
3. double click the segment again. 
4. you see an empty box. 
5. write something again.
6. the original note is gone. 

**Expected behavior**
like in the older version of VIAN, you can just add a note many times.

**Screenshots**

![image](https://user-images.githubusercontent.com/58776405/79538512-751a7b00-80bf-11ea-9688-32c88b715a1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version

**Comment by ghalter** [comment]
uff. good point!
as a work around, activate "multi segmentation" in the Timeline/Options.

![grafik](https://user-images.githubusercontent.com/14757659/79553497-ded55d80-809c-11ea-8672-e0479fe2081c.png)
