### ISSUE TITLE
Minor Bug Create >> Create Experiments

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#284]
The selection Create >> Create Experiment does not seem to function anymore.

**Comment by ghalter** [comment]
This is probably, because multiple Experiments are turned off by default. 
Can you check if it works when you turn it on in Preferences->Behaviour->Multi Experiments

**Comment by ghalter** [comment]
If this is the problem, we should also disable the create experiment button when multi experiments is turned off.

**Comment by JonathanSchaber** [comment]
Still not working when checked «Allow Multiple Experiments»

**Comment by ghalter** [comment]
The button should now be updated correctly. 
The create experiment at least on my side works as expected
