### ISSUE TITLE
Loading of AudioExtraction

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#289]
AudioExtraction gets not saved to the project --> needs to be computed everytime the project is reloaded. It gets also not displayed under «Analyses» in the Outliner.

**Comment by ghalter** [comment]
Yes, this is currently expected, since the AudioExtraction is really not elaborate currently. 
We will have to rethink this in a future run. 
As soon as there will be any additional functionality towards audio, we will expose the audio extraction to the analyses

**Comment by JonathanSchaber** [comment]
implemented
