### ISSUE TITLE
Letterbox applied to screenshots

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#300]
It would be of advantage to have the screenshots also with the black portions of the frame, otherwise you have to extract them at a later stage.

**Comment by ghalter** [comment]
This is now the default when exporting screenshots. 
It can be disabled in the Screenshot exporter dialog. 
When no letterbox is set prior to export, the user is informed, and the original frame is exported. 

c8c55b090840ce6377d4418e66d86c96cbeadf09
