### ISSUE TITLE
Feature: Display Annotations in Inspector

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#301]
It would be nice if the annotations would be visible in the Inspector for a given element (I know, with the new classification timeline-tool there is a workaround, but still)

**Comment by ghalter** [comment]
By annotations you mean the classification?

**Comment by JonathanSchaber** [comment]
yes

**Comment by ghalter** [comment]
This is now implemented: 
2d404fb687b189edde6259a4b1fbcf64036f99be

![grafik](https://user-images.githubusercontent.com/14757659/89025064-7ac26680-d326-11ea-89e1-d05a38eb388c.png)
