### ISSUE TITLE
Info Widget

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#303]
It would be helpful sometimes to have an «Info»-Widget (maybe under File >> Information), that displays different properties of the current project, such as:

- template used
- number of segments per segmentation
- number of screenshots per tier
- ...

**Comment by ghalter** [comment]
Let me know if there is any other information we should include

**Comment by JonathanSchaber** [comment]
can be considerer closed, if new items should appear, they are probably quickly introduced
