### ISSUE TITLE
Analyses: Names & Display

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#304]
The analyses seem to be a little bit confusing at the moment:
- the names do not always correspond (analysis >> «color average» is called «color features» in outliner after being computed)
- generally, the names are (at least to me) not informative about what is being computed (e.g. why is histogram a 2D analysis, but palette a 3D?)

- all analyses should be display in one analyses-widget (now, some analyses are displayed only in inspector, and some are also displayed in the analyses-widget)

**Comment by ghalter** [comment]
This is now implemented, Analyses can only be added once per classification object to a certain entity

**Comment by ghalter** [comment]
And are indicated with<Analysis> (<ClassificationObject>)
