### ISSUE TITLE
Auto segmentation problem

### ISSUE THREAD

**Issue by aleksanderkoren** [ghalter/VIAN#305]
Auto segmentation no longer works on my MacOS Catalina, version 10.15.6. I had this issue before, relating to file format, but now it no longer works regardless of file format.

After creating a new project and starting colorimetry, I pause the colorimetry and click auto segmentation based on color histogram. The progress bar starts and goes from 1-100% and VIAN says "Auto segmentation job finished", but nothing actually happens. If I try to finish the whole colorimetry first, the colorimetry will freeze a few minutes before it should finish. 

<img width="1435" alt="Skjermbilde 2020-08-06 kl  11 59 34" src="https://user-images.githubusercontent.com/58776456/89733056-2ff5cc80-da53-11ea-85c8-33755de9880a.png">
<img width="1440" alt="Skjermbilde 2020-08-06 kl  11 59 49" src="https://user-images.githubusercontent.com/58776456/89733062-3d12bb80-da53-11ea-9a58-d5ba35319aa4.png">
<img width="1436" alt="Skjermbilde 2020-08-06 kl  12 11 24" src="https://user-images.githubusercontent.com/58776456/89733085-5451a900-da53-11ea-8842-fb8f4bb9414c.png">

**Comment by JonathanSchaber** [comment]
@aleksanderkoren do you still have this problem? I had this issue too, but now it's working again.

**Comment by aleksanderkoren** [comment]
I have tried a selection of different projects/files, and it does seem to consistently work now. Even mkv files!
