### ISSUE TITLE
Feature: Shortcut for centering & Scaling

### ISSUE THREAD

**Issue by JonathanSchaber** [ghalter/VIAN#322]
In different situations, it would be helpful to have one keystroke that would center and scale the acitve widget (e.g. in the timeline -> hit key and whole movie is scales to timeline, cursor in middle / in analysis widget: during 3D inspection you get «lost» -> hit key and you see the whole point cloud centered in the widget)

**Comment by ghalter** [comment]
In general this is the [F] key, however in both widgets it is not implemented yet,

**Comment by ghalter** [comment]
95d90eed5f68439557449852c768031010a23bcd

**Comment by ghalter** [comment]
This is fixed
