### ISSUE TITLE
Auto Segmentation Dialog Improvements

### ISSUE THREAD

**Issue by ghalter** [ghalter/VIAN#328]
- Default "Color Distribution"
- Color Histogram -> Color Distribution
- Cluster Range -> Number of Segments between [x] and [y]
- Auto Frame when done
- First Entry Overflow Slider

**Comment by ghalter** [comment]
The corresponding Dialog is here: 
https://github.com/ghalter/VIAN/blob/8001f3b95635a4c725e571060eb79ce9921b7a9f/core/concurrent/auto_segmentation.py#L74

The .UI file is in  VIAN/qt_ui/DialogAutoSegmentation.ui 

Renaming can be done in the Qt designer.

**Comment by JonathanSchaber** [comment]
Can be considerer closed
