### ISSUE TITLE
Dialogue Should Close After Auto-segmentation Applied

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#334]
Once the the auto-segmentation is adjusted and applied the dialogue box remains open, should close though.

**Comment by JonathanSchaber** [comment]
I think the idea was that several segmentations could be generated at once - but if there is rarely the need for it,I agree, it  would probably be better if it closed automatically.

**Comment by flueko** [comment]
Yes, in general only one.

**Comment by JonathanSchaber** [comment]
Is implemented
