### ISSUE TITLE
Duration Calculation Wrong in XLS / Sequence Protocol Export

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#383]
Duration is calculated correctly in segmentation export csv, but wrong in xls / sequence protocol export.
<img width="500" alt="Screen Shot 2021-11-21 at 21 39 45" src="https://user-images.githubusercontent.com/30805626/142806814-1a6f853a-6899-4d6f-9218-444b3f78ffde.png">

**Comment by ghalter** [comment]
I replaced the segment.duration attributed with a computed property, this should remove inconsistencies
